
#minimal_mistakes_skin: "mint"
locale: "en"

title: "Francois' Portfolio"
subtitle: "Technical, content and UX writer"
name: "Francois Zucco"
email: "francois.zucco@hotmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  "Portfolio for my technical, content and other writing."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fpzed.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: "FPZED/FPZed.github.io"
logo: ""
words_per_minute: 200
breadcrumbs: true

linkedin_username: "www.linkedin.com/in/fpzucco"
github_username:  FPZed

# Site Author
author:
  name             : "Francois Zucco"
  avatar           : "/assets/images/avatar.png"
  bio              : >-
    I am technical and content writer, focusing on educating and guiding users – through intuitive UX design
    and writing, guides and articles. (User centric) … goal is to put the user first… the internet is a big 
    place with lots of writing, and my goal is to make a positive contribution that leads to painless and even
    helpful experiences, be it using business software, navigating a website, or learning.
  location         : "Toronto, Ontario"
  #email            : "Francois.Zucco@hotmail.com"
  links:
    #- label: "Email"
    #  icon: "fas fa-fw fa-envelope-square"
    #  url: "mailto:your.francois.zucco@hotmail.com"
    - label: "Resume"
      icon: "far fa-fw fa-file-pdf" #add some colour to these
      # url: "https://twitter.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/fpzucco"
    #- label: "GitHub"
      #icon: "fab fa-fw fa-github"
      # url: "https://github.com/FPZed"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Reading Files
include:
  - .htaccess
  - _pages
  - assets/fonts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Collections setup
collections:
  technical-writing:
    output: true
    permalink: /technical-writing/:name/
    #type: document
  content-writing:
    output: true
    permalink: /content-writing/:name/
  ux-writing:
    output: true
    permalink: /ux-writing/:name/
  creative:
    output: true
    permalink: /creative/:name/
    
sass:
  sass_dir: _sass


# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache



defaults:
  - scope:
      path: ""
    values:
      layout: home
      navigation: main




# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false